version: '3.8'

services:
  client-server1:
    build:
      context: .
      dockerfile: Dockerfile  # Usa el Dockerfile específico del servidor
    container_name: client-server1
    command: ["tail", "-f", "/dev/null"]  # Mantener el contenedor activo

  client-server2:
    build:
      context: .
      dockerfile: Dockerfile  # Usa el Dockerfile específico del cliente
    container_name: client-server2
    command: ["tail", "-f", "/dev/null"]  # Mantener el contenedor activo