version: '3.8'

services:
  client-server1:
    build:
      context: .
      dockerfile: Dockerfile  # Usa el Dockerfile específico del servidor
    container_name: client-server1
    stdin_open: true
    tty: true

  client-server2:
    build:
      context: .
      dockerfile: Dockerfile  # Usa el Dockerfile específico del cliente
    container_name: client-server2
    stdin_open: true
    tty: true